max_tune_length: 2048

model_name_or_path: "deepseek-ai/DeepSeek-Prover-V1.5-SFT"
tokenizer_name_or_path: "deepseek-ai/DeepSeek-Prover-V1.5-SFT"
trust_remote_code: True

trainer:
  tracker:
    type: wandb
    project: "STP_deepseek"
    name: "deepseek-sft"
    tags: ["deepseek-ai/DeepSeek-Prover-V1.5-SFT", "STP"]

  mp: p=f32,c=bfloat16

  train_batch_size: 2048
  num_train_steps: 115
  steps_per_eval: 10

  tensor_parallel_axes: ["mlp", "heads"]
  per_device_eval_parallelism: 8
  per_device_parallelism: 8
save_freq: 115

optimizer:
  learning_rate: 1e-4
  weight_decay: 0.0
  beta1: 0.9
  beta2: 0.95
  epsilon: 1E-5
  warmup: 20
  min_lr_ratio: 1.0